FROM node:22.3.0

WORKDIR /app

# Instalar dependências necessárias para compilar bcrypt
RUN apt-get update && apt-get install -y \
    python3 \
    make \
    g++ \
    gcc \
    && rm -rf /var/lib/apt/lists/*

COPY package*.json ./

# Instalar todas as dependências
RUN npm install

COPY . .

EXPOSE 3000

CMD ["npm", "run", "start:dev"]