version: '3.8'

services:
  app:
    container_name: carteira-financeira-app-dev
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=password
      - DB_NAME=carteira_financeira
      - JWT_SECRET=Senha@123
      - JWT_EXPIRES_IN=1h
      - PORT=3000
      - NODE_ENV=development
      - API_PREFIX=api
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start:dev
    depends_on:
      - postgres
    networks:
      - carteira-network

  postgres:
    container_name: carteira-financeira-postgres-dev
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=carteira_financeira
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - carteira-network

networks:
  carteira-network:
    driver: bridge

volumes:
  postgres_data: